# frozen_string_literal: true

# Generated by `rails generate phronomy:install`.
# Stores conversation messages keyed by thread_id.
class PhronomyMessage < ApplicationRecord
  include Phronomy::ActiveRecord::ActsAs
  acts_as_phronomy_message
end
