# frozen_string_literal: true

# Generated by `rails generate phronomy:install`.
# Stores graph checkpoint state keyed by thread_id.
class PhronomyCheckpoint < ApplicationRecord
  include Phronomy::ActiveRecord::ActsAs
  acts_as_phronomy_checkpoint
end
