# frozen_string_literal: true

source "https://rubygems.org"

eval_gemfile File.expand_path("../Gemfile.phronomy", __dir__)

gem "activerecord", "~> 8.1.3"
gem "pg", "~> 1.6"
gem "rake", "~> 13.2"
gem "rspec", "~> 3.13"
