# frozen_string_literal: true

require "phronomy"

# State shared across all graph nodes in the code-review pipeline.
class ReviewState
  include Phronomy::WorkflowContext

  # Path to the file being reviewed.
  field :file_path,      type: :replace, default: -> { "" }
  # Full source code string.
  field :source_code,    type: :replace, default: -> { "" }
  # Chunks produced by the splitter (Array of Hashes).
  field :chunks,         type: :replace, default: -> { [] }
  # Reviewer outputs keyed by perspective.
  field :reviews,        type: :merge,   default: -> { {} }
  # User-chosen priority: security / performance / readability / abstraction.
  field :priority,       type: :replace, default: -> { nil }
  # Improved code generated by ImproverAgent.
  field :improved_code,  type: :replace, default: -> { nil }
  # Application-level quality scores. These are not Phronomy::Testing::Eval.
  field :quality_scores, type: :merge,   default: -> { {} }
end
